apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-3lpu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-3lpu
    app.kubernetes.io/part-of: tkrw-pr712-0075-0067-app
  name: devfile-sample-3lpu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-3lpu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-3lpu
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-3lpu@sha256:67f71bb68ef4e505f8effcd5ca17e083d142336bc73ae3f1dcbd1eaf18515f77
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
