apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-3lpu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0067-tenant/tkrw-pr712-0075-0067-app/devfile-sample-3lpu@sha256:67f71bb68ef4e505f8effcd5ca17e083d142336bc73ae3f1dcbd1eaf18515f77
        name: my-nodejs
        resources: {}
status: {}
